use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'LZBSegmentBar_Example' do
  pod 'LZBSegmentBar', :path => '../'

  target 'LZBSegmentBar_Tests' do
    inherit! :search_paths

    
  end
end
